[schema]
name = "overture-schema-building"
version = "0.1.0"
license = "CC-BY-4.0"
description = "Overture building feature type"
homepage = "https://overturemaps.org"
repository = "https://github.com/OvertureMaps/schema"
documentation = "https://docs.overturemaps.org/schema"

[dependencies]
overture-schema-core = "^1.2.1"

[[example.building]]
id          = "123"
geometry    = { "type": "Polygon", coordinates: [] }
names       = { "primary": "le tour Eiffel" }
color       = "black"
sources     = [ { property = "", dataset = "OpenStreetMap", record_id = "r@123" ]

[[example.building]]
id          = "456"
geometry    = { "type": "Polygon", coordinates: [] }
names       = { "primary": "Empire State Building" }
color       = "gray"
sources     = [ { property = "", dataset = "OpenStreetMap", record_id = "r@456" ]

[[example.building]]
id          = "789"
geometry    = { "type": "Polygon", coordinates: [] }
sources     = [ { property = "", dataset = "OpenStreetMap", record_id = "r@456" ]



